### ISSUE TITLE
Question about abbreviation of Target

### ISSUE THREAD

**Issue by zihos** [HannahKirk/Hatemoji#1]
Hi,
Thank you for your work.
This dataset is a very interesting set!

Where can I find the full text of Target represented by the abbreviation?
I don't know what "indig" , "ethmin", etc stand for.

Best regards,
Jiho Park.

**Comment by HannahKirk** [comment]
Hi there!

This was the [guidance ](https://docs.google.com/spreadsheets/d/17bi7WAC4kU9v6p3XPQJ8IeHuwAlq6r_ddBQPe4HoiZU/edit?usp=sharing)provided to our annotators: 

All the best,

Hannah
